spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_center
    username: postgres
    password: 123456
server:
  port: 8081

mybatis:
  mapper-locations: /mapper/*.xml